title: J. Andrew Crain
email: me@j.andrewcrain.com
description: >-
  J. Andrew Crain site description
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://j.andrewcrain.com" 
lang: en_US
twitter:
  username: j_andrewcrain
  card: summary

plugins:
  - jekyll-feed
  - jekyll-seo-tag

include:
  - _redirects

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
